{
  "openapi": "3.0.3",
  "info": {
    "title": "Todolist API",
    "version": "1.0.0",
    "description": "Todolist API",
    "termsOfService": "http://swagger.io/terms/",
    "contact": {
      "name": "API Support",
      "url": "http://www.swagger.io/support",
      "email": "6R4lJ@example.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0"
    }
  },
  "servers": [
    {
      "description": "Todolist API",
      "url": "http://{envitonment}.todolist.localhost:3000",
      "variables": {
        "envitonment": {
          "default": "dev",
          "enum": ["dev", "test", "prod"]
        }
      }
    }
  ],
  "externalDocs": {
    "description": "Find out more about Swagger",
    "url": "http://swagger.io"
  },
  "paths": {
    "/todolist": {
      "get": {
        "security": [
          {
            "TodolistAuth": []
          }
        ],
        "tags": ["Todolist"],
        "summary": "Get all todolists",
        "description": "Get all todolists by default",
        "parameters": [
          {
            "name": "include_done",
            "in": "query",
            "required": false,
            "description": "Is include done todolist",
            "schema": {
              "type": "boolean",
              "nullable": true,
              "default": false
            }
          },
          {
            "name": "name",
            "in": "query",
            "required": false,
            "description": "Filter todolist by name",
            "schema": {
              "type": "string",
              "nullable": true,
              "minLength": 1,
              "maxLength": 100
            },
            "examples": {
              "java": {
                "description": "Example name java",
                "value": "java"
              },
              "php": {
                "description": "Example name php",
                "value": "php"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success get all todolist",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ArrayTodoList"
                },
                "examples": {
                  "success": {
                    "description": "Success get all todolist",
                    "value": [
                      {
                        "id": "1",
                        "name": "java",
                        "priority": 3,
                        "tags": ["Java", "Programming"]
                      },
                      {
                        "id": "2",
                        "name": "php",
                        "priority": 3,
                        "tags": ["Php", "Programming"]
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "TodolistAuth": []
          }
        ],
        "tags": ["Todolist"],
        "summary": "Create a new todolist",
        "description": "Create a new todolist to database",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateOrUpdateTodoList"
              },
              "examples": {
                "java": {
                  "description": "Example name java",
                  "value": {
                    "name": "java",
                    "priority": 1,
                    "tags": ["java", "Programming"]
                  }
                },
                "php": {
                  "description": "Example name php",
                  "value": {
                    "name": "php",
                    "priority": 1,
                    "tags": ["php", "Programming"]
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success create new todolist",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Todolist"
                },
                "examples": {
                  "java": {
                    "description": "Success create java todolist",
                    "value": {
                      "id": "1",
                      "name": "java",
                      "priority": 3,
                      "tags": ["Java", "Programming"]
                    }
                  },
                  "php": {
                    "description": "Success create php todolist",
                    "value": {
                      "id": "2",
                      "name": "php",
                      "priority": 3,
                      "tags": ["php", "Programming"]
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/todolist/{todoListId}": {
      "put": {
        "security": [
          {
            "TodolistAuth": []
          }
        ],
        "tags": ["Todolist"],
        "summary": "Update a todolist",
        "description": "Update a todolist",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateOrUpdateTodoList"
              },
              "examples": {
                "java": {
                  "description": "Example name java",
                  "value": {
                    "name": "java",
                    "priority": 1,
                    "tags": ["java", "Programming"]
                  }
                },
                "php": {
                  "description": "Example name php",
                  "value": {
                    "name": "php",
                    "priority": 1,
                    "tags": ["php", "Programming"]
                  }
                }
              }
            }
          }
        },
        "parameters": [
          {
            "$ref": "#/components/parameters/todoListId"
          }
        ],
        "responses": {
          "200": {
            "description": "Success update new todolist",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Todolist"
                },
                "examples": {
                  "java": {
                    "description": "Success create java todolist",
                    "value": {
                      "id": "1",
                      "name": "java",
                      "priority": 3,
                      "tags": ["Java", "Programming"]
                    }
                  },
                  "php": {
                    "description": "Success create php todolist",
                    "value": {
                      "id": "2",
                      "name": "php",
                      "priority": 3,
                      "tags": ["php", "Programming"]
                    }
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "TodolistAuth": []
          }
        ],
        "tags": ["Todolist"],

        "summary": "Delete a todolist",
        "description": "Delete a todolist",
        "parameters": [
          {
            "$ref": "#/components/parameters/todoListId"
          }
        ],
        "responses": {
          "200": {
            "description": "Success delete todolist",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    }
                  }
                },
                "examples": {
                  "success": {
                    "description": "Success delete todolist",
                    "value": {
                      "success": true
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Failed Delete not found todolist",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    }
                  }
                },
                "examples": {
                  "failed": {
                    "description": "Failed delete todolist",
                    "value": {
                      "success": false
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "TodolistAuth": {
        "description": "Authentication for Todolist RESTful API",
        "type": "apiKey",
        "in": "header",
        "name": "X-API-Key"
      }
    },
    "parameters": {
      "todoListId": {
        "name": "todolistId",
        "in": "path",
        "required": true,
        "description": "Todolist id for updated",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 100
        },
        "examples": {
          "java": {
            "description": "Example name java",
            "value": "1"
          },
          "php": {
            "description": "Example name php",
            "value": "2"
          }
        }
      }
    },
    "schemas": {
      "Todolist": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "priority": {
            "type": "number",
            "format": "int32"
          },
          "tags": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      },
      "CreateOrUpdateTodoList": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "priority": {
            "type": "number",
            "format": "int32"
          },
          "tags": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      },
      "ArrayTodoList": {
        "type": "array",
        "items": {
          "ref": "#/components/schemas/Todolist"
        }
      }
    }
  }
}
